### Öğrenci oluştur
POST http://localhost:3000/api/ogrenci
Content-Type: application/json

{
  "ad": "Nur",
  "soyad": "Karaarslan",
  "numara": "2028042",
  "bolum": "ell"
}

### Tüm öğrencileri listele
GET http://localhost:3000/api/ogrenci

### Tek öğrenci getir
GET http://localhost:3000/api/ogrenci/5

### Öğrenci güncelle
PUT http://localhost:3000/api/ogrenci/5
Content-Type: application/json

{
  "soyad": "Güler"
}

### Öğrenci sil
DELETE http://localhost:3000/api/ogrenci/1